### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [CleverPumpkin/CrunchyCalendar#10]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by iMofas** [comment]
Hello!

We appreciate your help with logo ) 
You can send your concepts to my email denis @ cleverpumpkin.ru

**Comment by mansya** [comment]
I have design logo for this project. what do you think ? do you like it ? which one do you like ? If there is a change. please let me know.
![crunchycalendar](https://user-images.githubusercontent.com/33461607/44943959-520f5a80-adf9-11e8-8873-2e4ec405e66d.png)

**Comment by mansya** [comment]
how about the logo. I really hope for a positive response from you.
