### ISSUE TITLE
Performance drawbacks

### ISSUE THREAD

**Issue by smbduknow** [CleverPumpkin/CrunchyCalendar#13]
Try to implement calendar on nested RecyclerViews (outer RV+LinearLayoutManager hold month items & every month has its own inner RV+GridLayoutManager with its days) and compare performance of both implementation. Your variant with single RV+GridLayoutManager is much slower

**Comment by alexsurinov** [comment]
Thanks, it's interesting issue. 
On what device did you test calendar performance? Could you share your test app with nested RecyclerViews?

**Comment by smbduknow** [comment]
I've tested on Samsung Galaxy Note 3 but unfortunately I can't share my implementation at this moment because of NDA. However you can compare your calendar with https://github.com/ApplikeySolutions/CosmoCalendar for example (it based on the same idea)
Try to check case with fast scrolling
