### ISSUE TITLE
How to display a single month?

### ISSUE THREAD

**Issue by LeoColman** [CleverPumpkin/CrunchyCalendar#15]
Is there a way to display a single month, such as
![image](https://user-images.githubusercontent.com/1577251/51443683-e52b2d00-1cd3-11e9-8319-2cc18b75fbd0.png)

?

I want to create an events-like calendar, and I want the user to browse month by month, as I'll display information below the calendar.

Is this possible / planned with Crunchy?

**Comment by alexsurinov** [comment]
@Kerooker Hi!

> Is there a way to display a single month

You can easily customize the calendar with min and max date to display only a single month. 
Please, look at the sample of usage here: https://github.com/CleverPumpkin/CrunchyCalendar#usage

> I want to create an events-like calendar, and I want the user to browse month by month, as I'll display information below the calendar.

If you want to implement page-like calendar such as the one on your screenshot, may be CruncyCalendar is not the best choice. It has been designed as a calendar with "infinite" vertical scroll and there are no alternative ways to display dates on the calendar. At the moment we are not planning adding alternative ways of calendar displaying.

**Comment by LeoColman** [comment]
Thanks a lot for your time to answer me, @rAseri ! I found Crunchy beautiful. It's unfortunate that it won't cut the deal for me right now. I'll keep myself openminded :D
