### ISSUE TITLE
Can I add a selection programmatically?

### ISSUE THREAD

**Issue by bellierjonathan** [CleverPumpkin/CrunchyCalendar#18]
Hello,

I would like to select all the week (Monday to sunday) when a user clicks on a day.

I'm trying to select all days with `onDateClickListener` and `setupCalendar` but it's not work.

Do you have any idea? :/

**Comment by alexsurinov** [comment]
Hi! 
In the current implementation the only way to setup prgrammatically preselected dates it's the `CalendarView.setupCalendar` method. It isn't the best way, but you can try to use this method to achieve what you want.

Anyway, it would be good to be able to setup preselected dates with some public method / property. I'll think about adding separate method for preselected dates in the next version.

**Comment by bellierjonathan** [comment]
Ok cool! Thanks for your answer 😉 I will check again tomorrow.

**Comment by bellierjonathan** [comment]
For week selection I made a pull request. I tried to define same way as you go.

https://github.com/CleverPumpkin/CrunchyCalendar/pull/22

**Comment by alexsurinov** [comment]
The new version of the library (2.0.0-beta1) has been released. 
https://github.com/CleverPumpkin/CrunchyCalendar/releases/tag/v2.0.0-beta1

Now you can update selected dates with a new `CalendarView.updateSelectedDates` method.
