### ISSUE TITLE
Remove Month label/empty space

### ISSUE THREAD

**Issue by JayadevHaddadi** [CleverPumpkin/CrunchyCalendar#19]
Hi,
First of all thank you for providing such a nice calendar for the people.

I would like it if it was possible to remove the month label and the extra wasted spaces that defines a new month. It would be nice if the month could be presented transparently behind the month or at some other place.

Thank you

**Comment by alexsurinov** [comment]
Hi and thanks for your suggestion. The calendar's UI has been designed as it is, and I'm not shure that we will change it in the nearest future.
