### ISSUE TITLE
Event indicator types and increased indicator count

### ISSUE THREAD

**Issue by austinaryain** [CleverPumpkin/CrunchyCalendar#26]
I've been working with Crunchy Calendar for a couple days and am fitting it into my use case where I need square event indicators and possibly more than 4 indicators showing on each calendar cell. 

Is this something that you might have on the roadmap for this library or would you be willing to look at a PR if I had some suggested changes to have event indicator types?  Or would I be better off maintaining my fork separately?

**Comment by alexsurinov** [comment]
Hi and thank you for the suggestion! 

I think we'll consider the ability of adding some sort of indicators customisation, but at the moment I'm not sure how it should be implemented. I think that PR isn't nessessery.

Please note, that for some custom drawing logic (custom event indicators in your case) you can use library `AbsDateItemDecoration` class. You can extend this class and implement your drawing logic in the `AbsDateItemDecoration.decorateDateView` method. After that you can add your decoration class using `CalendarView.addCustomItemDecoration` method.

**Comment by IlmarsAut** [comment]
Hi.
i was wondering if it is possible to create events with two colors(layer-list) or image instead of color(int)?
