### ISSUE TITLE
Timezone settings

### ISSUE THREAD

**Issue by wyzard** [CleverPumpkin/CrunchyCalendar#27]
Hello again!

How can we deal with different timezones? Is there any built-in solution or what is the suggested method?

Thank you.

**Comment by alexsurinov** [comment]
Hello! 

At the moment the Calendar uses default time zone and locale that have been set up on the device. There is no API for setting different time zone or locale in the current implementation. 

Could you describe your use case with different time zone?

**Comment by wyzard** [comment]
Hello!

Thank you for your answer.
Currently we are working on a booking system (backend is based on PHP & MySQL). Every registered host can set his own timezone in the profile settings.
In the android app users can view any of the host's reservation calendar. In this view I have to show the reserved dates/events based on the timezone set in the host's settings, not in the mobile user's locale.

**Comment by alexsurinov** [comment]
Ok, I got it. I think it makes sense and I'll think about adding timezone setting in the next minor version. 
Keep the issue open.

**Comment by wyzard** [comment]
Ok, thank you for your help! :)

**Comment by tfalamu** [comment]
Hello, are you accepting contributions for this issue?

**Comment by iMofas** [comment]
> Hello, are you accepting contributions for this issue?

Yes!
