### ISSUE TITLE
create event in calendar

### ISSUE THREAD

**Issue by pavelsust** [CleverPumpkin/CrunchyCalendar#29]
Hello,
From server i got some date and i want to show this date as a event and mark it. I want to use java but i can't find a helpful sample to add event into the calendar. 
I am stack on this. say i have a array of date i want to show this date into the calendar with a mark

Thanks in advance

**Comment by alexsurinov** [comment]
Hi there!

To display your custom event on the Calendar you have to create a class that represents your custom event and  implements the `CalendarView.DateIndicator` interface. Doing that, you'll be able to add instances of the event class to the Calendar:
```java
 List<EventItem> eventItems = generateEventItems()
 calendarView.setDatesIndicators(generateEventItems());
```
I've added a sample that demonstrates how to display events on the Calendar using Java.
You can find the sample [here](https://github.com/CleverPumpkin/CrunchyCalendar/blob/events-displaying-java/sample/src/main/java/ru/cleverpumpkin/calendar/sample/events/EventListDemoJavaFragment.java).

**Comment by pavelsust** [comment]
thanks a lot

**Comment by pavelsust** [comment]
i got an error during compile your code
error: incompatible types: List<EventItem> cannot be converted to List<? extends DateIndicator>

**Comment by alexsurinov** [comment]
That's strange.  I have just cloned the repo, build the sample app and there is no error on my machine. Please, provide the full build log output.

**Comment by pavelsust** [comment]
you can check this demo.
https://github.com/paveltech/EventCalender

**Comment by alexsurinov** [comment]
I checked your demo app. Could you give me a write access to your repo to push a fix for your demo app?

**Comment by pavelsust** [comment]
ya sure
