### ISSUE TITLE
Logo Design: CrunchyCalendar

### ISSUE THREAD

**Issue by baranpirincal** [CleverPumpkin/CrunchyCalendar#3]
Hello!

I examined your project and I saw that Crunchy Calendar has no logo design yet. I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by iMofas** [comment]
Hi, Baran!

Thanks for your idea!
Feel free to contact with me via email — denis [at] cleverpumpkin.ru

**Comment by baranpirincal** [comment]
Hey again!

I made a logo design for CrunchyCalendar.

Idea is "C" letter and Calendar.

I am waiting your comments!

![asdasdasd](https://user-images.githubusercontent.com/37786733/43669433-a5c878b6-978b-11e8-8399-d8ee4defbc11.jpg)

Best Regards
Baran Pirinçal

**Comment by baranpirincal** [comment]
@iMofas I'm still waiting! :)
