### ISSUE TITLE
Date Range Selection and dateSelectionFilter

### ISSUE THREAD

**Issue by polatolu** [CleverPumpkin/CrunchyCalendar#30]
Hi,

Thanks for the great library.

Is it possible to disallow users to select date ranges if one or more of the days in the selected range is not selectable?

So, let's say, I'm setting my dateSelectionFilter to not allow selecting date `17/06/2019`. In that case, user should not be able to select a range like between `15/06/2019` and `19/06/2019` or a wider range because that one not selectable day is in the range. 

I checked and couldn't find a solution for it. Is it possible to do that at the moment or do we need an update?

I can still manually achieve this by after user makes a range selection, I can loop through the selected days and check them one-by-one, but just wondered if the CalendarView have this feature already.

**Comment by alexsurinov** [comment]
Hi and thank you!

At the current version there is no suitable api to achieve what you want "out of the box". And I think this is not a common use case to implement it in the library. But, as you said, you can implement this scenario by manually checking selected dates and updating dates range accordingly.

**Comment by polatolu** [comment]
Thank you. 

I implemented it by the way I explained above and it is working fine.
