### ISSUE TITLE
Not scrolling to current day.

### ISSUE THREAD

**Issue by pixelsbyweb** [CleverPumpkin/CrunchyCalendar#31]
Hi.
In setupCalendar() if initialDate and minDate are too far apart then it won't scroll to initialDate.
For example.
Set calendar with minDate as 1st of January of this year and initialDate as today (August 1st) then when loaded it won't scroll to today.
moveToDate() also won't scroll to that date.

Now, if we initialize calendar with minDate set as March and initialDate as August then when loaded we will see August on the screen.

I guess it has something to do with how many items recyclerView loads because after we scroll to today it all works fine.

**Comment by alexsurinov** [comment]
Hi and thanks for the issue! 
I have fixed it.  You can check it out in the `develop` branch. Please, let me know if anything else will be found.

**Comment by alexsurinov** [comment]
I have released  new version `2.0.1` with this fix.

**Comment by fury0928** [comment]
Hi, rAseri. 
That didn't work even I use the version 2.0.1.
Can you tell me the exact way?

**Comment by pixelsbyweb** [comment]
Works for me just fine.

**Comment by fury0928** [comment]
Could you send me the sample code so that I can implement?

**Comment by fury0928** [comment]
calendar_view.setupCalendar(
                        initialDate = initialDate,
                        selectionMode = CalendarView.SelectionMode.NONE,
                        firstDayOfWeek = Calendar.MONDAY
                    )

I tried with this code but it doesn't go to initialDate.
only showing at first page.

**Comment by alexsurinov** [comment]
@AceBerry924 Hi!
 
That's strange. Here is the sample code of setting custom initial date:
```kotlin
override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        // Prepare custom initial date.
        val calendar = Calendar.getInstance()
        calendar.set(2015, Calendar.JANUARY, 18)
        val initialDate = CalendarDate(calendar.time)

        if (savedInstanceState == null) {
            calendarView.setupCalendar(
                // Set the custom initial date.
                initialDate = initialDate,
                selectionMode = CalendarView.SelectionMode.NONE
            )
        }
    }
```
You can also peruse the sample app, custom initial date is used in many samples.

**Comment by fury0928** [comment]
Oh, thank you. rAseri
All working fine now.
I just made mistake :)
