### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by guney1911** [CleverPumpkin/CrunchyCalendar#32]
Is there a way to translate or set the names of the months and days? This is such a great project and I hope someone can help me.

**Comment by alexsurinov** [comment]
Hi there!
Months and days are translated according to a device locale. Could you clarify, what kind of translations do you need?

**Comment by guney1911** [comment]
Exactly that kind but I didn't know that it is handled automatically. That
is another great aspect of this library .
Thank you for your fast response
