### ISSUE TITLE
How to select and deselect multiple dates in month

### ISSUE THREAD

**Issue by eureka0928** [CleverPumpkin/CrunchyCalendar#35]
Hello, rAseri, I can select multiple dates but cannot deselect date.
Could you tell me the way to do that?

**Comment by alexsurinov** [comment]
Hello!
Can you describe the problem in more detail? You are trying to deselect a date programmatically or by tapping on the already selected date?

**Comment by fury0928** [comment]
rAseri.
I tap on the already selected date.
I showed Snackbar after selecting date and after showing Snackbar, unselect not working anymore.

**Comment by alexsurinov** [comment]
I can't reproduce this issue. Could you share your code/project with me to be able to reproduce this issue locally?
