### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [CleverPumpkin/CrunchyCalendar#4]
I get this error:

![image](https://user-images.githubusercontent.com/5357526/43690548-5b95e49c-9914-11e8-80f6-7f3a816358a8.png)

**Comment by DevAhamed** [comment]
Kindly mention the Android Studio version and AGP version you are using. This will be easy for the maintainers to respond back.

**Comment by AndroidDeveloperLB** [comment]
Android Studio 3.3 Canary 4
Build #AI-182.3208.16.33.4924367, built on August 1, 2018
JRE: 1.8.0_152-release-1136-b05 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by DevAhamed** [comment]
Canary AGP plugin requires kotlin plugin v1.2.50. So try to use the stable android studio version.

**Comment by AndroidDeveloperLB** [comment]
OK please make it work with newer versions too.
I've noticed other issues with the sample:
1. When choosing RTL language such as Hebrew ("עברית"), the arrow icon of the up-button is in the wrong direction.
2. When scrolling fast, it always stops at some point, and a bit later allows to scroll more. This is a bit annoying, as on Google Calendar, it allows to freely scroll without interruptions.

**Comment by alexsurinov** [comment]
@AndroidDeveloperLB thanks a lot for your feedback!
We'll update Kotlin version in the nearest future. Other issues, that you mentioned, also will be investigated.

**Comment by AndroidDeveloperLB** [comment]
Thank you.
