### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by eikaramba** [CleverPumpkin/CrunchyCalendar#5]
thx for the library i just wanted to share our requirements, maybe it is interesting for you. All come from real business cases:
- being able to quickly navigate years(e.g. to select birthday without needing to scroll/click thousand times)
- filter to select what dates should not be allowed. either by manually specifying dates or provide defaults((e.g. weekends, holidays)

**Comment by alexsurinov** [comment]
@eikaramba thanks for your suggestions!

1. `CalendarView` provides `moveToDate()` method that can be used for fast moving to the specific calendar date. You can implement your custom UI logic for year selection and use this Calendar method for moving to the first date of selected year. 

2. This is a very good suggestion, we'll think about it.

**Comment by alexsurinov** [comment]
@eikaramba In version 1.1.0 we have added the features that you suggested:
1. We have added an optional year selection control that uses for fast year switching.
2. We have added a `dateSelectionFilter `. That filter is used to detect whether a date available for selection or not. You can implement your custom filtration logic.
