### ISSUE TITLE
How to set "firstdayofweek"

### ISSUE THREAD

**Issue by chrisonline** [CleverPumpkin/CrunchyCalendar#6]
Thanks for this great library.

I have just added it to my project but I don't find a way to set the first day of week.
How is this possible?

**Comment by alexsurinov** [comment]
@chrisonline the first day of week is set automatically from default device Locale. There is no ability to set the first day of week manually at current version of the library.

**Comment by chrisonline** [comment]
Ok thanks for the info.

Can you please add such a feature?
In my app the user can manually set the locale and the first day of week.

**Comment by alexsurinov** [comment]
Thanks for suggestion. I think we'll be able to add this functionality in the next version if it is really required feature.

**Comment by chrisonline** [comment]
Great, thank you.
For me it is really required because in my app you can set your own language.

Some users wants for example as langauge english but they live in Austria.
So after changing to english you get as first day "Sunday", but in Austria the first day is "Monday.

**Comment by alexsurinov** [comment]
In version 1.1.0 we have added optional `firstDayOfWeek` parameter to the `setupCalendar()` method. Hope it helps you.
