### ISSUE TITLE
Possible to add a "LongClickListener"

### ISSUE THREAD

**Issue by chrisonline** [CleverPumpkin/CrunchyCalendar#7]
Can you please add a "LongClickListener" for the date selection?

A click selects the date but I have added the indicators and want to show the "Events" on this day with  a long click of the user.

So short click selects the date and long click would open a popup with the events.

**Comment by alexsurinov** [comment]
Yes, it's possible. We will add this listener in the next version. 
Also feel free to make your own pull request with a feature suggestion :)

**Comment by alexsurinov** [comment]
A "LongClickListener" was added in 1.1.0
