### ISSUE TITLE
Theme Dark problems - Customizing all colors does not work

### ISSUE THREAD

**Issue by chrisonline** [CleverPumpkin/CrunchyCalendar#8]
How can I set the weekend background colors?

If I use a dark theme I get this output out of the box:
![image](https://user-images.githubusercontent.com/2077218/44402895-5747ec00-a553-11e8-822e-50c568986714.png)

So I need to set some colors that it looks OK:
**Month Text Label Color** --> app:calendar_month_text_color --> working
**Date Text Color** --> app:calendar_date_text_color --> not working --> working with a selector
**Date Background** --> app:calendar_date_background --> working

Weekend Date Background --> ?? 

Output is at the moment:
![image](https://user-images.githubusercontent.com/2077218/44404133-80b64700-a556-11e8-9dc6-a8fc68f5c7f6.png)

**Comment by alexsurinov** [comment]
@chrisonline To set up custom background for weekend date you should declare you own date background selector and define state for `weekend`:
```xml
<item app:calendar_state_weekend="true">
    <color android:color="@color/custom_calendar_date_weekend_background" />
</item>
```

To set up custom text color for weekend date you should declare date text color selector and also define state for `weekend`:
```xml
<item android:color="@color/custom_calendar_date_weekend_text_color" app:calendar_state_weekend="true" />
```

Please, peruse the source code of the sample app for more details. You can find an example of working with custom styles on the  `Custom styles` section of the sample app.

**Comment by chrisonline** [comment]
Thanks it works now.
