### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by antonshkurenko** [CleverPumpkin/CrunchyCalendar#9]
First of all, thanks for the library :)

Please, add more possibilities for theming:

1) Make properties public, to allow theming from code, not xml only
2) Do not ignore defStyleAttr from the constructor, right now it just goes to the super classes, but is ignored in the "obtainStyledAttributes" in init block

**Comment by alexsurinov** [comment]
Thanks for the feedback! 
1. It isn't only about public properties, but it also required  some serious internal changes. I think it's a good suggestion, we'll think about this feature implementation.
2. Could you clarify, why `obtainStyledAttributes`  version with `defStyleAttr` is preferred?

**Comment by antonshkurenko** [comment]
Related to p2
You can't pass custom style in the constructor, if you want to style all calendars with the same theme in the app

**Comment by alexsurinov** [comment]
Calendar style customization options have been improved in version 2.0.0. 
Thanks for your suggestions!
